# Generated by Django 4.1.3 on 2022-12-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsstory_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='image_url',
            field=models.URLField(default='https://www.scotsman.com/webimg/b25lY21zOjY0N2NiYTc5LTFhMmMtNGIwZC04NjZiLWE5MTVlODQ4OGJjYjpkMjBlYmQ5My02Yzg2LTRiOTAtODU2My02MzU2N2VlMjY3ZTU=.jpg?quality=65&smart&width=990'),
            preserve_default=False,
        ),
    ]
